/****** Object:  Table [dbo].[hackney_address]    Script Date: 04/04/2019 12:32:33 ******/
CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE dbo.address_base (
    uprn double precision not null,
    parent_uprn double precision,
    udprn double precision,
    usrn double precision not null,
    toid character varying(20),
    classification_code character varying(6),
    easting numeric(12,4),
    northing numeric(12,4),
    latitude numeric(12,9),
    longitude numeric(12,9),
    rpc character varying(10),
    last_update_date date,
    single_line_address character varying(800),
    po_box character varying(18),
    organisation character varying(100),
    sub_building character varying(120),
    building_name character varying(100),
    building_number character varying(17),
    street_name character varying(100),
    locality character varying(100),
    town_name character varying(100),
    post_town character varying(100),
    change_code character varying(8),
    island character varying(8),
    postcode character varying(8),
    delivery_point_suffix character varying(8),
    gss_code character varying(100)
); 

CREATE TABLE dbo.hackney_address(
     lpi_key character varying(14) not null,
     lpi_logical_status character varying(18),
     lpi_start_date integer not null,
     lpi_end_date integer not null,
     lpi_last_update_date integer not null,
     usrn integer,
     uprn bigint not null,
     parent_uprn bigint,
     blpu_start_date integer not null,
     blpu_end_date integer not null,
     blpu_class character varying(4),
     blpu_last_update_date integer not null,
     usage_description character varying(160),
     usage_primary character varying(160),
     property_shell boolean not null,
     easting double precision not null,
     northing double precision not null,
     unit_number character varying(17),
     sao_text character varying(90),
     building_number character varying(17),
     pao_text character varying(90),
     paon_start_num smallint,
     street_description character varying(100),
     locality character varying(100),
     ward character varying(100),
     town character varying(100),
     postcode character varying(8),
     postcode_nospace character varying(8),
     planning_use_class character varying(50),
     neverexport boolean not null,
     longitude double precision not null,
     latitude double precision not null,
     gazetteer character varying(8),
     organisation character varying(100),
     line1 character varying(200),
     line2 character varying(200),
     line3 character varying(200),
     line4 character varying(100)
);

/****** Object:  Table [dbo].[national_address]    Script Date: 04/04/2019 12:32:33 ******/
CREATE TABLE dbo.national_address(
     lpi_key character varying(14) not null,
     lpi_logical_status character varying(18),
     lpi_start_date integer not null,
     lpi_end_date integer not null,
     lpi_last_update_date integer not null,
     usrn integer,
     uprn bigint not null,
     parent_uprn bigint,
     blpu_start_date integer not null,
     blpu_end_date integer not null,
     blpu_class character varying(4),
     blpu_last_update_date integer not null,
     usage_description character varying(160),
     usage_primary character varying(160),
     property_shell boolean not null,
     easting double precision not null,
     northing double precision not null,
     unit_number character varying(17),
     sao_text character varying(90),
     building_number character varying(17),
     pao_text character varying(90),
     paon_start_num smallint,
     street_description character varying(100),
     locality character varying(100),
     ward character varying(100),
     town character varying(100),
     postcode character varying(8),
     postcode_nospace character varying(8),
     planning_use_class character varying(50),
     neverexport boolean not null,
     longitude double precision not null,
     latitude double precision not null,
     gazetteer character varying(8),
     organisation character varying(100),
     line1 character varying(200),
     line2 character varying(200),
     line3 character varying(200),
     line4 character varying(100)
);

/****** Object:  Table [dbo].[hackney_xref]    Script Date: 04/04/2019 12:32:33 ******/
CREATE TABLE dbo.hackney_xref(
	xref_key varchar(14) NULL,
	uprn float NOT NULL,
	xref_code varchar(6) NULL,
	xref_name varchar(100) NULL,
	xref_value varchar(50) NULL,
	xref_end_date timestamp NULL
);
create view dbo.combined_address as  SELECT * FROM dbo.hackney_address   UNION ALL  SELECT * FROM dbo.national_address;
